<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Soal extends Model
{
	protected $table = 'soals';
    protected $primaryKey = 'id_soal';
    // protected $fillable = {
    // 	'jenis_soal','no_soal','pertanyaan','jwb_a','jwb_b','jwb_c','jwb_d','kunci','gambar','id_quiz','id_modul','materi_nama','id_modul'
    // }

    // public function jawaban()
    // {
    //     return $this->hasMany(\App\JawabanSoalQuiz::class);
    //     // return $this->hasOne('Jawaban');
    // }

    public function jawaban()
    {
        return $this->belongsToMany(\App\JawabanSoalQuiz::class, 'jawaban_soal_quizs', 'id_soal');
    }

    public function jawabans()
    {
        return $this->belongsTo(\App\JawabanSoalQuiz::class, 'jawaban_soal_quizs');        
    }


    //autogenerated this function...
    public function nilaiQuizPilgan()
    {
        return $this->belongsToMany('NilaiQuizPilihanGandaTrainee', 'nilai_quiz_pilgan_trainees');
        // return $this->hasOne('SoalHasLembar');
    }

    public function soalhasquiz()
    {
        return $this->belongsToMany(\App\Quiz::class, 'soal_has_quizs', 'id_quiz', 'id_soal');
        // return $this->hasOne('SoalHasLembar');
    }

}
