<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Soal extends Model
{
	protected $table = 'soals';
    protected $primaryKey = 'id_soal';
    // protected $fillable = {
    // 	'jenis_soal','no_soal','pertanyaan','jwb_a','jwb_b','jwb_c','jwb_d','kunci','gambar','id_ujian','id_modul','materi_nama','id_modul'
    // }

    // public function jawaban()
    // {
    //     return $this->hasMany(\App\JawabanSoalUjian::class);
    //     // return $this->hasOne('Jawaban');
    // }

    public function jawaban()
    {
        return $this->belongsToMany(\App\JawabanSoalUjian::class, 'jawaban_soal_ujians', 'id_soal');
    }

    public function jawabans()
    {
        return $this->belongsTo(\App\JawabanSoalUjian::class, 'jawaban_soal_ujians');        
    }


    //autogenerated this function...
    public function nilaiUjianPilgan()
    {
        return $this->belongsToMany('NilaiUjianPilihanGandaTrainee', 'nilai_ujian_pilgan_trainees');
        // return $this->hasOne('SoalHasLembar');
    }

    public function soalhasujian()
    {
        return $this->belongsToMany(\App\Ujian::class, 'soal_has_ujians', 'id_ujian', 'id_soal');
        // return $this->hasOne('SoalHasLembar');
    }

}
